Areas/Admin/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShop.Models;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using BookShop.Models.UnitOfWork;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Routing;

namespace BookShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorsController : Controller
    {
        private readonly IUnitOfWork _UW;
        private readonly string NotFoundMessage ="چنین نویسنده ای وجود ندارد.";

        public AuthorsController(IUnitOfWork UW)
        {
            _UW = UW;
        }

        //[ActionName("Author-Index")]
        public async Task<IActionResult> Index(int page = 1, int row = 10)
        {
            var Authors = _UW.BaseRepository<Author>().FindAllAsync();
            var PagingModel = PagingList.Create(await Authors, row, page);
            PagingModel.RouteValue = new RouteValueDictionary
            {
                {"row",row},
            };

            var isAjax = Request.Headers["X-Requested-With"] == "XMLHttpRequest";
            if (isAjax)
                return PartialView("_AuthorsTable", PagingModel);


            return View("Index",PagingModel);

        }

        public IActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AuthorID,FirstName,LastName")] Author author)
        {
            if (ModelState.IsValid)
            {
                await _UW.BaseRepository<Author>().CreateAsync(author);
                await _UW.Commit();
                TempData["notification"] = "درج اطلاعات با موفقیت انجام شد.";
            }
            return PartialView("_Create", author);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                ModelState.AddModelError(string.Empty, NotFoundMessage);

            var author = await _UW.BaseRepository<Author>().FindByIDAsync(id);

            if (author == null)
                ModelState.AddModelError(string.Empty, NotFoundMessage);
            return PartialView("_Edit", author);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AuthorID,FirstName,LastName")] Author author)
        {

            if (id != author.AuthorID)
                ModelState.AddModelError(string.Empty, NotFoundMessage);

            if (ModelState.IsValid)
            {
                try
                {
                    _UW.BaseRepository<Author>().Update(author);
                    await _UW.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await _UW.BaseRepository<Author>().FindByIDAsync(author.AuthorID) == null)
                        return NotFound();
                    else
                        throw;
                        
                }
                TempData["notification"] = "ویرایش اطلاعات با موفقیت انجام شد.";
            }
            return PartialView("_Edit", author);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                ModelState.AddModelError(string.Empty, NotFoundMessage);
            var author = await _UW.BaseRepository<Author>().FindByIDAsync(id);
            if (author == null)
            {
                ModelState.AddModelError(string.Empty, NotFoundMessage);
                return NotFound();
            }

            return PartialView("_Delete", author);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var Author= await _UW.BaseRepository<Author>().FindByIDAsync(id);
            if(Author==null)
                return NotFound();

            else
            {
                _UW.BaseRepository<Author>().Delete(Author);
                await _UW.Commit();
                TempData["notification"] = "حذف اطلاعات با موفقیت انجام شد.";
                return PartialView("_Delete", Author);
            }
        }


        private List<EntityStates> DisplayStates(IEnumerable<EntityEntry> entities)
        {
            List<EntityStates> EntityStates = new List<EntityStates>();
            foreach(var entry in entities)
            {
                EntityStates states = new EntityStates()
                {
                    EntityName = entry.Entity.GetType().Name,
                    EntityState=entry.State.ToString(),
                };

                EntityStates.Add(states);
            }

            return EntityStates;
        }

        public async Task<IActionResult> AuthorBooks(int id)
        {

            // Enable LazyLoading 
            var Author = _UW.BaseRepository<Author>().FindByIDAsync(id);
            if(Author==null)
            {
                return NotFound();
            }

            else
            {
                return View(await Author);
            }
          
        }

        public IActionResult Notifacation()
        {
            return PartialView("_Notifacation",TempData["notification"]);
        }
    }
}

Areas/Admin/Pages/Publishers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookShop.Models;
using BookShop.Models.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookShop.Areas.Admin.Pages.Publishers
{
    public class CreateModel : PageModel
    {
        private readonly IUnitOfWork _UW;
        public CreateModel(IUnitOfWork UW)
        {
            _UW = UW;
        }

        [BindProperty]
        public Publisher Publisher { get; set; }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }

            await _UW.BaseRepository<Publisher>().CreateAsync(Publisher);
            await _UW.Commit();

            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Publishers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookShop.Models;
using BookShop.Models.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookShop.Areas.Admin.Pages.Publishers
{
    public class EditModel : PageModel
    {
        private readonly IUnitOfWork _UW;
        public EditModel(IUnitOfWork UW)
        {
            _UW = UW;
        }

        [BindProperty]
        public Publisher Publisher { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }

            var IsExitPublisher = await _UW.BaseRepository<Publisher>().FindByIDAsync(id);
            if(IsExitPublisher!=null)
            {
                Publisher= await _UW.BaseRepository<Publisher>().FindByIDAsync(id);
                return Page();
            }

            else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }

            else
            {
                var Publishers = await _UW.BaseRepository<Publisher>().FindByIDAsync(Publisher.PublisherID);
                if(Publishers!=null)
                {
                    Publishers.PublisherName = Publisher.PublisherName;
                    await _UW.Commit();
                    return RedirectToPage("./Index");
                }

                else
                {
                    return NotFound();
                }
            }
        }
    }
}

Areas/Admin/Views/Authors/AuthorBooks.cshtml
@model Author
@{
    ViewData["Title"] = "AuthorBooks";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-light">
                کتاب های @Model.FirstName   @Model.LastName
            </div>
            <div class="card-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>عنوان کتاب</th>
                            <th>شابک</th>
                            <th>ناشر</th>
                            <th>زبان</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Author_Books)
                        {
                            @if (item.Book != null)
                            {
                                <tr>
                                    <td>@item.Book.Title</td>
                                    <td>@item.Book.ISBN</td>
                                    <td>@item.Book.Publisher.PublisherName</td>
                                    <td>@item.Book.Language.LanguageName</td>
                                </tr>
                            }

                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Authors/Create.cshtml
@model BookShop.Models.Author

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-light">
                افزودن نویسنده جدید
            </div>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="card-footer clearfix bg-light text-right">
                    <button type="submit" class="btn btn-info float-left">افزودن نویسنده</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/Authors/Delete.cshtml
@model BookShop.Models.Author

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


<div class="row w-75 m-auto">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-light">حذف اطلاعات</div>
            <div class="card-body">
                <p>آیا شما می خواهید <span> @Model.FirstName  @Model.LastName را از لیست نویسندگان حذف کنید ؟ </span> </p>
            </div>

            <div class="card-footer bg-light text-right clearfix">
                <form asp-action="Delete">
                    <input type="hidden" value="@Model.AuthorID" name="id" />
                    <input type="submit" value="بله" class="btn btn-danger mr-2 float-left" />
                    <a asp-action="Index" class="btn btn-info float-left">خیر</a>
                </form>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Authors/Details.cshtml
@model BookShop.Models.Author

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Author</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AuthorID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/Authors/Edit.cshtml
@model BookShop.Models.Author

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-light">
                ویرایش اطلاعات نویسنده 
            </div>
            
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/Authors/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<BookShop.Models.Author>
@using ReflectionIT.Mvc.Paging
@addTagHelper*,ReflectionIT.Mvc.Paging
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<div id="modal-placeHolder">

</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header bg-light">
                نویسندگان
            </div>
            <div class="card-body">
                <p>
                    <button data-url="@Url.Action("Create")" data-toggle='ajax-modal' class="btn btn-info btn-icon">
                        <i class="fa fa-plus text-white"></i> | افزودن نویسنده جدید
                    </button>
                </p>
                <div id="notification" data-url="@Url.Action("Notifacation")"></div>
                <div id="tableContent">
                    @await Html.PartialAsync("_AuthorsTable", Model);
                </div>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Authors/_AuthorsTable.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<BookShop.Models.Author>
@using ReflectionIT.Mvc.Paging

<table id="mytable" data-url="@Url.Action("index")" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.SortableHeaderFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th class="text-center">
                مشاهده کتاب ها
            </th>
            <th class="text-center">عملیات</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td class="text-center">
                    <a asp-action="AuthorBooks" asp-route-id="@item.AuthorID" class="btn btn-info btn-sm">مشاهده کتاب ها</a>
                </td>
                <td class="text-center">
                    <button type="button" class="btn btn-success btn-icon" data-toggle="ajax-modal" data-url="@Url.Action("Edit","Authors",values:new {id=item.AuthorID})">
                        <i class="fa fa-edit text-white"></i>
                    </button>
                    <button type="button" class="btn btn-danger btn-icon" data-toggle="ajax-modal" data-url="@Url.Action("Delete","Authors",values:new {id=item.AuthorID})">
                        <i class="fa fa-trash text-white"></i>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>
<nav>
    @await this.Component.InvokeAsync("Pager", new { PagingList = this.Model })
</nav>

Areas/Admin/Views/Authors/_Create.cshtml
@model BookShop.Models.Author

<style> /*chon modal dar har jayie momken ast baz shavad var ejra shavad style shadow track datalist styles.css nmizarim*/
    .modal-header .close {
        padding: 0rem;
        margin: 0rem 0rem 0rem 0;
    }
</style>

<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5  class="modal-title col-8">افزودن نویسنده جدید</h5>
                <button type="button" class="close col-2" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" value="@ViewData.ModelState.IsValid.ToString()" name="IsValid" />
                    <div class="card-body">
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label asp-for="FirstName" class="control-label"></label>
                                <input asp-for="FirstName" class="form-control" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-12">
                                <label asp-for="LastName" class="control-label"></label>
                                <input asp-for="LastName" class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer clearfix bg-light text-right">
                        
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success ml-1" data-save="modal">افزودن</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Authors/_Delete.cshtml
@model BookShop.Models.Author
    <style>
        /*chon modal dar har jayie momken ast baz shavad var ejra shavad style shadow track datalist styles.css nmizarim*/
        .modal-header .close {
            padding: 0rem;
            margin: 0rem 0rem 0rem 0;
        }
    </style>

<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">حذف کتاب</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body">
                <p>آیا شما می خواهید <span> @Model.FirstName  @Model.LastName را از لیست نویسندگان حذف کنید ؟ </span> </p>
                <form asp-action="Delete">
                    <input type="hidden" value="@Model.AuthorID" name="id" />
                    <input type="hidden" name="IsValid" value="True" />
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-success ml-1" data-save="modal">بله</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">خیر</button>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Authors/_Edit.cshtml
@model BookShop.Models.Author

<style>
    /*chon modal dar har jayie momken ast baz shavad var ejra shavad style shadow track datalist styles.css nmizarim*/
    .modal-header .close {
        padding: 0rem;
        margin: 0rem 0rem 0rem 0;
    }
</style>
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">ویرایش اطلاعات کتاب</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body">
                @if (ViewData.ModelState.IsValid == false)
                {
                    <div asp-validation-summary="ModelOnly" class="alert alert-danger mb-0"></div>
                }

                else
                {
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" value="@ViewData.ModelState.IsValid.ToString()" name="IsValid" />
                <input type="hidden" asp-for="AuthorID" />
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-12">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </form>
                }

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-success ml-1" data-save="modal">ذخیره تغییرات</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">بستن</button>
            </div>
        </div>
    </div>
</div>